version: "3.9"

services:
  chat-newbiz:
    build: .
    container_name: chat-newbiz
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    network_mode: host
    restart: unless-stopped

